[package]
name = "openvidu_sync"
version = "0.1.0"
edition = "2021"
authors = ["LeoYu"]
license = "MIT"
description = "OpenVidu recording sync tool"
readme = "README.md"
repository = "https://github.com/leoyu0607/Openvidu-record-sync"
keywords = ["openvidu", "sync", "recording"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
anyhow = "1.0.100"
serde_json = "1.0.145"
log = "0.4.28"
simplelog = "0.12.2"
time = "0.3.44"
